name: Scrape Dam Information Workflow

on:
  schedule:
    # Runs at 8:30 AM PH standard time every day.
    - cron: '30 0 * * *'  # 12:30 am UTC
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-dotnet@v4 #-python@v3
      # with:
      #   python-version: '3.8'  
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the scrape script
      run: python scrape_dam.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update data" -a || echo "No changes to commit"
        git push https://${{ secrets.DAM_TOKEN }}@github.com/marksm88/data_scrape.git
