name: Scrape Dam Information Workflow

on:
  schedule:
    # Runs at 9 AM PH standard time every day.
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the scrape script
      run: python scrape_dam.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update data" -a || echo "No changes to commit"
        git push https://${{ secrets.DAM_TOKEN }}@github.com/marksm88/data_scrape.git
